import { UserProfile } from "./types";

export const profiles: UserProfile[] = [
  {
    id: "maya-chen",
    emoji: "👩‍💻",
    name: "Maya Chen",
    age: 27,
    occupation: "Software Engineer",
    location: "Austin, TX",
    maritalStatus: "Single",
    householdSize: 1,
    shortBio: "Young professional tackling student loans while trying to start investing and save for a condo.",
    income: 135000,
    housing: {
      type: "renter",
      monthlyPayment: 2200,
    },
    debts: [
      { name: "Student Loans", balance: 87000, rate: 5.5 },
      { name: "Credit Card", balance: 3200, rate: 22.99 },
    ],
    assets: [
      { name: "401(k)", balance: 18500 },
      { name: "High-Yield Savings", balance: 12000 },
      { name: "HSA", balance: 2800 },
    ],
    creditScore: 740,
    goals: [
      "Pay off student loans strategically",
      "Start investing (Roth IRA)",
      "Save for a condo down payment",
    ],
    suggestedQuestions: [
      "Should I pay off my student loans or start investing first?",
      "How should I open and fund a Roth IRA?",
      "What's a realistic timeline to save for a condo?",
    ],
  },
  {
    id: "patel-family",
    emoji: "👨‍👩‍👧‍👦",
    name: "James & Priya Patel",
    age: "38/36",
    occupation: "Marketing Director + Nurse",
    location: "Raleigh, NC",
    maritalStatus: "Married",
    householdSize: 4,
    shortBio: "Dual-income family balancing mortgage, kids' college savings, and retirement planning.",
    income: 175000,
    incomeNote: "Combined",
    housing: {
      type: "homeowner",
      monthlyPayment: 1850,
      homeValue: 380000,
    },
    debts: [
      { name: "Mortgage", balance: 295000, rate: 3.25 },
      { name: "Student Loans", balance: 22000, rate: 4.5 },
      { name: "Car Loan", balance: 18500, rate: 5.9 },
      { name: "Credit Cards", balance: 6800, rate: 21.99 },
    ],
    assets: [
      { name: "James's 401(k)", balance: 85000 },
      { name: "Priya's 403(b)", balance: 42000 },
      { name: "529 Plans (2 kids)", balance: 14000 },
      { name: "Roth IRA", balance: 11500 },
    ],
    creditScore: "765/780",
    goals: [
      "Max out 529 contributions for both kids",
      "Pay off credit card debt",
      "Open a taxable brokerage account",
    ],
    suggestedQuestions: [
      "How much should we be putting into the kids' 529 plans?",
      "What's the best strategy to eliminate our credit card debt?",
      "Should we refinance our mortgage at current rates?",
    ],
  },
  {
    id: "desiree-washington",
    emoji: "💪",
    name: "Desiree Washington",
    age: 34,
    occupation: "Administrative Assistant",
    location: "Columbus, OH",
    maritalStatus: "Divorced",
    householdSize: 3,
    shortBio: "Single mom of two working hard to build financial stability and break the cycle of debt.",
    income: 48000,
    incomeNote: "+ $600/mo child support",
    housing: {
      type: "renter",
      monthlyPayment: 1350,
    },
    debts: [
      { name: "Student Loans", balance: 14000, rate: 5.0 },
      { name: "Credit Cards", balance: 8500, rate: 24.99 },
      { name: "Car Loan", balance: 9200, rate: 7.5 },
      { name: "Medical Debt", balance: 2300, rate: 0 },
    ],
    assets: [
      { name: "Old 401(k)", balance: 8500 },
      { name: "Savings Account", balance: 3200 },
    ],
    creditScore: 660,
    goals: [
      "Build a 3-month emergency fund",
      "Eliminate credit card debt",
      "Improve credit score to 720+",
    ],
    suggestedQuestions: [
      "How do I build an emergency fund on a tight budget?",
      "What's the fastest way to pay off my credit card debt?",
      "Should I roll over my old 401(k)?",
    ],
  },
  {
    id: "marcus-rivera",
    emoji: "🔨",
    name: "Marcus Rivera",
    age: 44,
    occupation: "Construction Project Manager",
    location: "Denver, CO",
    maritalStatus: "Divorced",
    householdSize: 1,
    shortBio: "Rebuilding financially after divorce — focused on crushing debt and getting back on track for retirement.",
    income: 92000,
    additionalExpenses: [{ name: "Child Support", amount: 1400 }],
    housing: {
      type: "renter",
      monthlyPayment: 1600,
    },
    debts: [
      { name: "Credit Cards", balance: 15000, rate: 22.99 },
      { name: "Car Loan", balance: 12000, rate: 6.5 },
      { name: "Personal Loan", balance: 8000, rate: 11.0 },
    ],
    assets: [
      { name: "401(k)", balance: 62000 },
      { name: "Roth IRA", balance: 4200 },
      { name: "Savings", balance: 5500 },
    ],
    creditScore: 690,
    goals: [
      "Crush credit card debt aggressively",
      "Rebuild 401(k) to pre-divorce levels",
      "Buy a home in 3-5 years",
    ],
    suggestedQuestions: [
      "What's the fastest way to pay off $35K in debt?",
      "How do I catch up on retirement savings after losing half?",
      "When can I realistically afford to buy a home again?",
    ],
  },
  {
    id: "nakamura-couple",
    emoji: "🏡",
    name: "Robert & Linda Nakamura",
    age: "59/57",
    occupation: "Senior Accountant + HS Principal",
    location: "Portland, OR",
    maritalStatus: "Married",
    householdSize: 2,
    shortBio: "Near-retirement couple optimizing their substantial savings for a comfortable, secure retirement.",
    income: 210000,
    incomeNote: "Combined",
    housing: {
      type: "homeowner",
      monthlyPayment: 2100,
      homeValue: 520000,
    },
    debts: [
      { name: "Mortgage", balance: 85000, rate: 2.75, monthlyPayment: 2100 },
    ],
    assets: [
      { name: "Robert's 401(k)", balance: 420000 },
      { name: "Linda's 403(b)", balance: 385000 },
      { name: "Traditional IRA", balance: 95000 },
      { name: "Roth IRA", balance: 78000 },
      { name: "Brokerage Account", balance: 65000 },
      { name: "HSA", balance: 18000 },
      { name: "State Pension (Linda)", balance: 0 },
    ],
    creditScore: "810/805",
    goals: [
      "Optimize retirement timing (both retire by 62)",
      "Social Security claiming strategy",
      "Roth conversion ladder before RMDs",
      "Medicare and healthcare planning",
    ],
    suggestedQuestions: [
      "When should we each start claiming Social Security?",
      "Should we do Roth conversions before retirement?",
      "How should we plan for healthcare costs before Medicare?",
    ],
  },
];
